import Link from "next/link"
import { motion } from "framer-motion"
import { BellRing, Glasses, Puzzle, X } from "lucide-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { ScrollArea } from "@/components/ui/scroll-area"

interface TransationModalProps {
  id: string
  onClick: () => void
}

export default function TransactionModal({
  id,
  onClick,
}: TransationModalProps) {
  return (
    <div className="absolute inset-0 z-30 flex select-none items-center justify-center">
      <motion.div
        key="image"
        layoutId={id}
        className="relative h-fit w-[70vw] select-none rounded-lg bg-background"
      >
        <Button
          className="absolute right-4 top-4 h-9 w-9 p-1"
          variant={"outline"}
          onClick={onClick}
        >
          <X size={16} />
        </Button>
        <Card className="w-full">
          <CardHeader>
            <CardTitle className="flex flex-col gap-2">
              <Label
                htmlFor="transaction-title"
                className=" text-muted-foreground "
              >
                Title is generated by GPT — Click to edit
              </Label>
              <Input
                id="transaction-title"
                value={"SOL Transfer"}
                className="w-[90%] border-none p-4 px-0 text-2xl focus:ring-0 focus-visible:ring-0"
                placeholder="SOL Transfer"
              />
            </CardTitle>
            <CardDescription className="flex flex-col gap-2">
              <div>
                Made by{" "}
                <Link
                  className="group relative  text-primary hover:underline"
                  href={
                    new URL(
                      `address/TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`,
                      "https://translator.shyft.to/"
                    )
                  }
                  target="_blank"
                >
                  Token Program
                </Link>{" "}
                8 minutes ago
              </div>
              <div className="flex gap-2">
                <Badge>Transaction Success</Badge>
                <Badge>SOL Transfer</Badge>
              </div>
            </CardDescription>
          </CardHeader>
          <CardContent className="">
            <ScrollArea className=" h-[300px] w-full">
              <div className="grid gap-3">
                {Array(10)
                  .fill(0)
                  .map((_, i) => (
                    <div
                      key={i}
                      className=" flex w-full space-x-4 rounded-md border p-4"
                    >
                      <BellRing />
                      <div className="flex-1 space-y-1">
                        <p className="text-sm font-medium leading-none">
                          Wrapper SOL
                        </p>
                        <p className="text-sm text-muted-foreground">
                          Hb2HDX6tnRfw5j442npy58Z2GBzJA58Nz7ipouWGT63p
                        </p>
                      </div>
                    </div>
                  ))}
              </div>
            </ScrollArea>
          </CardContent>
          <CardFooter className=" flex-row-reverse gap-2">
            <Button>
              <Puzzle className="mr-2 h-4 w-4" /> Mint transaction as NFT
            </Button>
            <Button variant={"outline"}>
              <Glasses className="mr-2 h-4 w-4" /> View on Shyft Transalator
            </Button>
          </CardFooter>
        </Card>
      </motion.div>
    </div>
  )
}
